services:
  django_gunicorn:
    volumes:
      - static:/staticfiles
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/staticfiles
      - /etc/letsencrypt/live/aldenluth.fi/fullchain.pem:/etc/letsencrypt/live/aldenluth.fi/fullchain.pem
      - /etc/letsencrypt/live/aldenluth.fi/privkey.pem:/etc/letsencrypt/live/aldenluth.fi/privkey.pem
    depends_on:
      - django_gunicorn

volumes:
  static:
